source "http://rubygems.org"
gem "nokogiri", ">=1.6.6.2"
gem "nmap-parser"
gem "rubyXL"
gem "ipaddress"
gem "rtf"
gem "ruport"
gem "kramdown"
gem "httparty"
gem "nessus-xmlrpc"
gem "mechanize"
gem "rubyzip"
gem "selenium-webdriver"
gem "headless"
gem "ruby-nmap"
gem "pry"

